### ISSUE TITLE
module has no attribute 'load'

### ISSUE THREAD

**Issue by HaraldTR** [promplate/hmr#6]
Trying to run uvicorn_hmr programmatically, but getting issues. On newest FastAPI / Starlette / uvicorn. 

```python
# __main__.py
from pathlib import Path
import sys
import uvicorn_hmr

if __name__ == "__main__":
    app_path = 'src.server:app'  
    cwd = Path.cwd()
    
    if str(cwd) not in sys.path:
        sys.path.insert(0, str(cwd))

    uvicorn_hmr.main(
        slug=app_path,
        host="0.0.0.0",
        port=8000,
        log_level="debug",
        reload_include=str(cwd / "src"),
        reload=False
    )
```

```python
Traceback (most recent call last):
  File "/venv/lib/python3.12/site-packages/uvicorn_hmr.py", line 91, in run_entry_file
    self.entry_module.load()
AttributeError: module 'src.server' has no attribute 'load'
```

**Comment by HaraldTR** [comment]
`reload=True` also gives me an error bc 

```python
runtime_js = Path(__file__, "../runtime.js").read_text()
```

has one to many `.` and does not resolve.

**Comment by CNSeniorious000** [comment]
Thank for reporting! I am looking into it.

**Comment by HaraldTR** [comment]
> Thank for reporting! I am looking into it.

Awesome 🏎️💨 Also, any thoughts about how hard it would be to implement for Celery? HMR would be suuuper powerful for fast celery reloads too. 

In general I think this package can do very well. I currently run a very large FastAPI project, and I have to do a lot of work to enable lazy imports to decrease startup times / reload times. With some of my libraries (data science stuff on the backend), this can take 45+ seconds without lazy imports, which is absolutely intolerable of course. I am surprised something like this has not shown up earlier.

**Comment by HaraldTR** [comment]
It looks like your reactive code is also using py3.14 generics syntax. Might it be a python version issue?

**Comment by CNSeniorious000** [comment]
Did you import the `src.server` module before calling `uvicorn_hmr.main()` in `__main__.py`? If so, I can [reproduce](https://github.com/CNSeniorious000/uvicorn-hmr-issue-6-repro) this issue.

The problem arises because `hmr` registers a new module loader to the import mechanism, making the module dependency graph visible. However, if `src.server` is imported first, it gets cached in `sys.modules` as a normal module, which `uvicorn-hmr` then uses.

To fix this, try adding the following code before importing `src.server`:

```py
from reactivity.hmr.core import patch_meta_path
patch_meta_path("./src/server")  # or "./src" or "."
```

If you prefer not to modify your existing code, you'll need to reload `src.server` and all its dependencies, as dependency information cannot be inferred from already-imported modules.

**Comment by CNSeniorious000** [comment]
> It looks like your reactive code is also using py3.14 generics syntax. Might it be a python version issue?

Nope, these packages are compatible and tested with `python>=3.12`

**Comment by CNSeniorious000** [comment]
> implement for Celery

Won't be hard, I think. Every integration only needs to override the `run_entry_file` method of a `Reloader` class (sorry for such a bad name😂), like the one I implemented for `uvicorn`:

https://github.com/promplate/hmr/blob/13787c3ab3074e1c5c7334533ee2240c12fedd95/packages/uvicorn-hmr/uvicorn_hmr.py#L83-L92

However, I haven't learned Celery yet, so the implementation might be delayed. **Contributions are welcome!** If you're unsure about how `hmr` works internally, I'm happy to explain.

---

Personally I have some heavy FastAPI servers too, which is my motivation to implement this ecosystem.

> I am surprised something like this has not shown up earlier.

So do I. HMR has accelerated JavaScript development for nearly a decade, yet I haven’t seen a similar tool in Python until now.

**Comment by HaraldTR** [comment]
> Did you import the `src.server` module before calling `uvicorn_hmr.main()` in `__main__.py`? If so, I can [reproduce](https://github.com/CNSeniorious000/uvicorn-hmr-issue-6-repro) this issue.
> 
> The problem arises because `hmr` registers a new module loader to the import mechanism, making the module dependency graph visible. However, if `src.server` is imported first, it gets cached in `sys.modules` as a normal module, which `uvicorn-hmr` then uses.
> 
> To fix this, try adding the following code before importing `src.server`:
> 
> from reactivity.hmr.core import patch_meta_path
> patch_meta_path("./src/server")  # or "./src" or "."
> If you prefer not to modify your existing code, you'll need to reload `src.server` and all its dependencies, as dependency information cannot be inferred from already-imported modules.

Yes! Thats it.

I still get an error though:

```python
Traceback (most recent call last):
  File "/venv/lib/python3.12/site-packages/reactivity/primitives.py", line 215, in <genexpr>
    return any(not isinstance(s, BaseDerived) or _pulled(s) for s in sub.subscribers)
                                                  ^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/reactivity/primitives.py", line 215, in _pulled
    return any(not isinstance(s, BaseDerived) or _pulled(s) for s in sub.subscribers)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/reactivity/primitives.py", line 215, in <genexpr>
    return any(not isinstance(s, BaseDerived) or _pulled(s) for s in sub.subscribers)
                                                  ^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/reactivity/primitives.py", line 215, in _pulled
    return any(not isinstance(s, BaseDerived) or _pulled(s) for s in sub.subscribers)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/reactivity/primitives.py", line 215, in <genexpr>
    return any(not isinstance(s, BaseDerived) or _pulled(s) for s in sub.subscribers)
                                                  ^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/reactivity/primitives.py", line 214, in _pulled
    def _pulled(sub: Subscribable):
RecursionError: maximum recursion depth exceeded
````

I also tried to not import app so I didnt have to patch the path, but ran into the same issue. I havent dived deep into the code yet so I couldnt immediately tell why this happens.

**Comment by HaraldTR** [comment]
> Won't be hard, I think. Every integration only needs to override the run_entry_file method of a Reloader class (sorry for such a bad name😂), like the one I implemented for uvicorn:

Yeah nice! If I can get this to work as a part of my project, I will for sure want to contribute here to make it work for celery too.

**Comment by CNSeniorious000** [comment]
> RecursionError: maximum recursion depth exceeded

Got it. It’s definitely due to a circular import. This is a bug in the HMR core, and I’ll fix it in the next few days when I have some free time.

**Comment by HaraldTR** [comment]
> > RecursionError: maximum recursion depth exceeded
> 
> Got it. It’s definitely due to a circular import. This is a bug in the HMR core, and I’ll fix it in the next few days when I have some free time.

Okay! I have a lot of imports in my project and typically import my packages in order to make sure I dont run into circular dependency issues. It might be that hmr resolves my modules and packages differently than how my project as a whole does it, or differently from python in general. Just a pointer! I will do some experiments myself, I will let you know if I figure anything out

**Comment by HaraldTR** [comment]
I think I might have found it!

1. reactivity/helpers.py line 127: self.track()
2. reactivity/primitives.py line 17: last.dependencies.add(self)
3. _weakrefset.py line 88: self.data.add(ref(item, self._remove))
4. _collections_abc.py line 834: return dict(self.items()) == dict(other.items())
5. Back to reactivity/helpers.py line 127: self.track()

This creates a circular dependency in the reactivity library itself. When adding an item to a dependency set, it triggers equality comparisons, which call items(), which calls track(), which tries to add to the dependency set again, creating an infinite recursion. I am pretty sure that is what is happening at least.

What do you think is the best way to fix it?

**Comment by CNSeniorious000** [comment]
Brilliant observation! It make sense. For the fix, consider adding a gloabl `_no_track = 0` flag in `primitives.py` and bypass tracking when `_no_track != 0`.

```py
@contextmanager
def untrack():
    primitives._no_track += 1  # noqa: SLF001
    try:
        yield
    finally:
        primitives._no_track -= 1  # noqa: SLF001
```

And wrap [`Subscribable.track`](https://github.com/promplate/pyth-on-line/blob/6a2d7574cebf640886eb3a912318d61ad3a9c401/src/python/common/reactivity/primitives.py#L15-L17) with this context manager?

```py
    if last is not self:
        with untrack():
            self.subscribers.add(last)
            last.dependencies.add(self)
```

Though somewhat inelegant.

---

BTW, I've never encountered this situation before. It would be very helpful if you could provide a minimal reproduction (for example, using only `Reactive`, `Derived`, and `Effect`).

---

Also, I noticed that the traceback you provided relates to the circular dependencies between `Derived` instances during triggering, not tracking. It seems we’ve uncovered two separate issues here 🤯

**Comment by HaraldTR** [comment]
> BTW, I've never encountered this situation before. It would be very helpful if you could provide a minimal reproduction (for example, using only Reactive, Derived, and Effect).

I was not able to reproduce this with a minimal example. However, I think the problem is due to this:

If I dont do the `src/server` import I will often get circular import issues, for example when running alembic migrations. This is because I have a set initialization order according to my project dependency rules. I do this in `__init__.py` and `__main__.py`. I init settings before database clients, before business logic for example. Trying to patch these imports using patch_meta_path, patch_module results in the same circular dependency issues. I assume hmr does not follow the ordering of imports that I want, and therefore get circular deps issues.

**Comment by CNSeniorious000** [comment]
Yes, during the initial import, the import order is respected. However, when there are file changes, module reloads doesn't follow import order, nor have I handled _deduplication_. Honestly, I haven’t fully figured out how to implement this properly.

To be specific, by "deduplication," I mean that currently, `__init__.py` and `__main__.py` are treated as mutual dependencies. So, when reloading `__init__.py`, I first reload `__main__.py`, and when reloading `__main__.py`, I first reload `__init__.py`... which causes infinite recursion.

I’ve been quite busy recently, and plan to resolve this circular triggering problem before May. I’ll update you once there is progress.

**Comment by HaraldTR** [comment]
> Yes, during the initial import, the import order is respected. However, when there are file changes, module reloads doesn't follow import order, nor have I handled _deduplication_. Honestly, I haven’t fully figured out how to implement this properly.
> 
> To be specific, by "deduplication," I mean that currently, `__init__.py` and `__main__.py` are treated as mutual dependencies. So, when reloading `__init__.py`, I first reload `__main__.py`, and when reloading `__main__.py`, I first reload `__init__.py`... which causes infinite recursion.
> 
> I’ve been quite busy recently, and plan to resolve this circular triggering problem before May. I’ll update you once there is progress.

Yeah, that sounds like the problems I am facing. Let me know if you need any additional information from me here.

**Comment by CNSeniorious000** [comment]
Hi @HaraldTR I just released hmr `v0.4.3`, which prevented recursion in the module dependency graph traversal. It works well in [a very simple test case](https://github.com/promplate/pyth-on-line/issues/255#issue-3011542347). Want to try it out?

**Comment by HaraldTR** [comment]
> Hi [@HaraldTR](https://github.com/HaraldTR) I just released hmr `v0.4.3`, which prevented recursion in the module dependency graph traversal. It works well in [a very simple test case](https://github.com/promplate/pyth-on-line/issues/255#issue-3011542347). Want to try it out?

Thanks for trying to fix this! I still get the recursion error when calling `patch_meta_path` or `patch_module`.

**Comment by CNSeniorious000** [comment]
Thanks for the new feedback! Are you sure you’ve updated to the latest `hmr` version in your venv? The traceback may be different now. Could you share the traceback you’re seeing?

---

There does exist some risk of infinite recursion in my code, but I’m concerned that making the logic over-complex could hurt maintainability. So I only fix for concrete problems to avoid premature optimization.

That’s why it’s important for me to understand how you handle “initialization.” If you can’t provide a minimal reproduction that you can share, could you describe what you actually do in your initialization code?

> This is because I have a set initialization order according to my project dependency rules. I do this in `__init__.py` and `__main__.py`. I init settings before database clients, before business logic for example.

As a hint, the way `hmr` works is mainly by tracking module-level variable access and modification.

Specifically, defining a name in a module triggers my `__setitem__` hook, while reading a name triggers my `__getitem__` hook.

So it would be really helpful if you could share any details about your initialization code. For example, do you both use and reassign variables from another module within a single module?

**Comment by CNSeniorious000** [comment]
@HaraldTR Nearly three months have passed since your last feedback, and quite a lot has changed in this library since then. Many known, unexpected, and anticipated bugs and performance issues have been resolved.

Based on my own testing, I believe that both the issue mentioned in the title and the subsequent recursion error should no longer occur—regardless of whether you use the CLI or manually invoke `uvicorn_hmr.main()`.

You can try out the latest versions (`uvicorn-hmr==0.0.8.1`, `hmr==0.6.4.4`) and let me know if the previous problems still persist. If I don’t hear back, or if everything works as expected, I plan to close this issue since I currently have no way to reproduce it.
If you encounter any new issues, please feel free to open a new one—since I don’t have access to any particularly large Python web apps for testing, any bug reports from your side would be especially valuable!

---

By the way, I happened to find an earlier email from you—before this issue—where you kindly asked about performance practices regarding HMR and lazy-loading. Unfortunately, it landed in my spam folder, so I missed it at the time. That was a great question! While I wasn’t able to give a definitive answer back then, I’m much more confident about it now.

All lazy-loading works exactly as you’d expect: for example, if you import a subpackage within a route handler, modifying files in that subpackage will not trigger a reload of the module containing that route handler. However, the route handler will use the updated subpackage.
In other words, you can simply think of `hmr` as always ensuring that **every import statement** will always get the latest module, but defers their execution until as late as possible.

Since uvicorn-hmr `v0.0.8`, I’ve also added logger output similar to `uvicorn --reload`, allowing you to see which modules were reloaded at INFO level and whether your main ASGI app instance was affected by these reloads at WARNING level—this determines whether the `uvicorn` server thread is restarted.

Everything is now much more transparent, and I hope that makes things a bit easier for your development!

**Comment by HaraldTR** [comment]
I'm still encountering issues with HMR and circular import detection in my FastAPI application. The error occurs during module loading where HMR seems to have trouble resolving certain module imports. These imports work fine with regular unicorn. 

```python
Traceback (most recent call last):
  File "src/server/api/server.py", line 55, in <module>
    from src.server.api.routers.workflow_endpoints import workflow_router
  File "/venv/lib/python3.12/site-packages/reactivity/hmr/core.py", line 151, in exec_module
    module.load()
  File "/venv/lib/python3.12/site-packages/reactivity/primitives.py", line 206, in __call__
    self.recompute()
  File "/venv/lib/python3.12/site-packages/reactivity/primitives.py", line 191, in recompute
    value = self.fn()
            ^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/reactivity/hmr/core.py", line 100, in __load
    exec(code, self.__namespace, self.__namespace_proxy)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/server/api/routers/workflow_endpoints.py", line 23, in <module>
    from src.manager.business.use_cases import handle_workflows, temporary_items
  File "/venv/lib/python3.12/site-packages/reactivity/hmr/core.py", line 151, in exec_module
    module.load()
  File "/venv/lib/python3.12/site-packages/reactivity/primitives.py", line 206, in __call__
    self.recompute()
  File "/venv/lib/python3.12/site-packages/reactivity/primitives.py", line 191, in recompute
    value = self.fn()
            ^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/reactivity/hmr/core.py", line 100, in __load
    exec(code, self.__namespace, self.__namespace_proxy)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/manager/business/use_cases/handle_workflows.py", line 24, in <module>
    from src.manager.core.use_cases.workflows import handle_processors
  File "/venv/lib/python3.12/site-packages/reactivity/hmr/core.py", line 151, in exec_module
    module.load()
  File "/venv/lib/python3.12/site-packages/reactivity/primitives.py", line 206, in __call__
    self.recompute()
  File "/venv/lib/python3.12/site-packages/reactivity/primitives.py", line 191, in recompute
    value = self.fn()
            ^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/reactivity/hmr/core.py", line 100, in __load
    exec(code, self.__namespace, self.__namespace_proxy)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/manager/core/use_cases/workflows/handle_processors.py", line 6, in <module>
    from src.data.processors.processor_service import ProcessorService
  File "/venv/lib/python3.12/site-packages/reactivity/hmr/core.py", line 151, in exec_module
    module.load()
  File "/venv/lib/python3.12/site-packages/reactivity/primitives.py", line 206, in __call__
    self.recompute()
  File "/venv/lib/python3.12/site-packages/reactivity/primitives.py", line 191, in recompute
    value = self.fn()
            ^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/reactivity/hmr/core.py", line 100, in __load
    exec(code, self.__namespace, self.__namespace_proxy)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/data/processors/processor_service.py", line 3, in <module>
    from src.data.processors.components import scheduler, items, general, config, handlers
  File "/venv/lib/python3.12/site-packages/reactivity/hmr/core.py", line 151, in exec_module
    module.load()
  File "/venv/lib/python3.12/site-packages/reactivity/primitives.py", line 206, in __call__
    self.recompute()
  File "/venv/lib/python3.12/site-packages/reactivity/primitives.py", line 191, in recompute
    value = self.fn()
            ^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/reactivity/hmr/core.py", line 100, in __load
    exec(code, self.__namespace, self.__namespace_proxy)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/data/processors/components/items.py", line 7, in <module>
    from src.data.processors.types.item_filter import ItemFilter, get_items
ModuleNotFoundError: No module named 'src.data.processors.types.item_filter'; 'src.data.processors.types' is not a package
```

My current setup uses:

```python
import builtins
import rich
import uvicorn_hmr
from reactivity.hmr.core import patch_meta_path

patch_meta_path(".")
from src.config import Environment, settings
from src.utils.debug import enable_debugpy

builtins.print = rich.print

if __name__ == "__main__":
    uvicorn_hmr.main(
        'src.server.api.server:app',
        host=settings.host,
        port=settings.port,
    )
```

Hopefully we'll be able to resolve the circular import issues on our side and get HMR up and running properly. The tool looks very promising for development workflow improvements once these module resolution issues are sorted out. Not sure it is that much more you can do on your side!

**Comment by CNSeniorious000** [comment]
Thanks @HaraldTR! That's weird—this time it is a `ModuleNotFoundError`. Is `src.data.processors.types` something unusual?

BTW, could you give me temporary access to your repository? It would help me investigate the issue more directly and better understand the root cause.

**Comment by HaraldTR** [comment]
> Thanks [@HaraldTR](https://github.com/HaraldTR)! That's weird—this time it is a `ModuleNotFoundError`. Is `src.data.processors.types` something unusual?
> 
> BTW, could you give me temporary access to your repository? It would help me investigate the issue more directly and better understand the root cause.

Its all just regular python code. Nothing special. Unfortunately I cant, because its my startups private company code.
